site_name: Java Notes
site_url: http://java.zayedbinhasan.me/
repo_url: https://github.com/frost23z/java

theme:
  name: material
  logo: 'media/icon/logo.png'
  favicon: 'media/icon/logo.png'
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode- exceptions.md

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.top

extra_css:
  - css/extra.css

watch:
  - includes

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.betterem
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - admonition
  - abbr
  - attr_list
  - def_list
  - md_in_html
  - tables

nav:
  - index.md
  - Basics:
    - 2_1_data_types.md
    - 2_2_conditionals.md
    - 2_3_arrays.md
  - strings.md
  - oop.md
  - additional.md
  - threads.md
  - collections.md